spring:
  profiles:
    active: default
    group:
      default: version,solace
      int: default,solace
      prod: default,solace
      local: default,local,solace

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:tms-ssp}?currentSchema=${DB_SCHEMA:public}
    username: ${DB_USERNAME:tms-ssp}
    password: ${DB_PASSWORD:tms-ssp}
  application:
    name: tms-ssp-chat
  main:
    banner-mode: off

  security:
    oauth2:
      client:
        registration:
          solace-backend:
            client-id: ${OAUTH2_APP_CONTEXT_CLIENT_ID}
            client-secret: ${OAUTH2_APP_CONTEXT_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - ${OAUTH2_APP_CONTEXT_SCOPE}
        provider:
          solace-backend:
            token-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/oauth2/v2.0/token
    resourceserver:
      jwt:
        issuer:
          - uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
            type: AZUREAD
            identifier: ${OAUTH_APP_ID:cf67f18c-947e-47f0-9d44-b278e43ecf48}
auth:
  oauth2:
    resourceserver:
      jwt:
        issuer:
          - uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
            type: AZUREAD
            identifier: ${OAUTH_APP_ID:cf67f18c-947e-47f0-9d44-b278e43ecf48}

restapi:
  solaceBackend:
    uri: ${TMS_SSP_SOLACE_BACKEND_URL:http://localhost:8442}

aws:
  bedrock:
    token: ${AWS_BEARER_TOKEN_BEDROCK}

rag:
  data:
    export-dir: ${EXPORT_DIR:data_export}
    transation:
      model-id: "eu.amazon.nova-pro-v1:0"
      temperature: 0.1
  rerank:
    model-id: "amazon.rerank-v1:0"
    min-score: 0.3 # Avoid poisoning the chat context with irrelevant results. Possible values 0-1
    max-results: 10 # Use only best results from rag, Don't overload chat context

  chat:
    model-id: "eu.amazon.nova-pro-v1:0"
    temperature: 0.1
    max-output-tokens: 1000
    translation:
      model-id: "eu.amazon.nova-lite-v1:0"
      temperature: 0.0

confluence:
  api:
    url: ${confluence.base-url}
    token: ${confluence.token}
  base-url: https://confluence.sbb.ch
  token: ${CONFLUENCE_TOKEN}
  start-page-id:
  - 1262683220 # sttrs messaging
  - 1257836039 # TRS Monitoring Alerting
  - 1769768106 # Architecture+Governance
  - 1916372937 # esta tekton pipeline
  - 3206067402 # aitg api provider

github:
  token: ${GITHUB_TOKEN}
  repositories:
    - https://github.com/SchweizerischeBundesbahnen/spring-cloud-stream-binder
    - https://github.com/solacecommunity/solace-prometheus-exporter
    - https://github.com/solacecommunity/spring-boot-starter-solace-client-config
    - https://github.com/solacecommunity/spring-cloud-stream-request-reply
    - https://github.com/solacecommunity/spring-solace-leader-election
    - https://github.com/solacecommunity/angular-solace-message-client

bitbucket:
  token: ${BITBUCKET_TOKEN}
  repositories:
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/tms-broker-deployment-engine/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/springcloudstream-examples/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/spring-boot-starter-time/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/api-documentation-maven-plugin/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/spring-boot-starter-logging-filter/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/spring-boot-starter-channel-metrics/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/solace-proxy/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/operator-solace-broker/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/operator-oracle-db/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/initial-load-cache/browse
    - https://code.sbb.ch/projects/TP_TMS_PLATTFORM/repos/hot-standby-manager/browse
    - https://code.sbb.ch/projects/TP_TMS_MONALESY/repos/monalesy-service-api/browse
    - https://code.sbb.ch/projects/TP_TMS_MONALESY/repos/monalesy-meter-solace-kpi-exporter/browse
    - https://code.sbb.ch/projects/TP_TMS_MONALESY/repos/monalesy-config-generator/browse
    - https://code.sbb.ch/projects/TP_TMS_MONALESY/repos/monalesy-service-description-provider/browse
    - https://code.sbb.ch/projects/TP_TMS_MONALESY/repos/monalesy-service-state-provider/browse
    - https://code.sbb.ch/projects/TP_TMS_MONALESY/repos/monalesy-openshift-monitoring-proxy/browse
    - https://code.sbb.ch/projects/TP_TMS_MONALESY/repos/monalesy-servicedescription-servicestate-operator/browse

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      solacekpi:
        abb1: tms
        abb2: plattform
        abb3: tms-ssp
        stage: ${TMS_STAGE:d}
        monalesy-stage: p
        groups:
          - keyframeInterval: PT15M
            incrementalSendInterval: PT30S
            groupName: chat
            metricInclusionsRegex:
              - .*
server:
  port: ${HTTP_PORT:8495}

logging:
  level:
    dev:
      langchain4j: ${LOG_LEVEL:INFO}
    ch:
      sbb: ${LOG_LEVEL:INFO}
      sbb.micrometer: ${KPI_LOG_LEVEL:INFO}
    org:
      springframework:
        web: ${LOG_LEVEL:INFO}
        http:
          client: ${LOG_LEVEL:INFO}
    com:
      solacesystems:
        jcsmp: ${SOLACE_LOG_LEVEL:WARN}
    root: ${LOG_LEVEL_ROOT:INFO}