spring:
  application:
    name: my-ai-spring-ai
  main:
    banner-mode: off

confluence:
  api:
    url: ${confluence.base-url}
    token: ${confluence.token}
  export-dir: messaging_support_export
  base-url: https://confluence.sbb.ch
  start-page-id: 1262683220 # sttrs messaging
  token: ${CONFLUENCE_TOKEN}

github:
  token: ${GITHUB_TOKEN}
  repositories:
    - https://github.com/SchweizerischeBundesbahnen/spring-cloud-stream-binder
    - https://github.com/solacecommunity/solace-prometheus-exporter
    - https://github.com/solacecommunity/spring-boot-starter-solace-client-config
    - https://github.com/solacecommunity/spring-cloud-stream-request-reply
    - https://github.com/solacecommunity/spring-solace-leader-election
    - https://github.com/solacecommunity/angular-solace-message-client

aws:
  bedrock:
    token: ${AWS_BEARER_TOKEN_BEDROCK}

rag:
  chat:
    model-id: "eu.amazon.nova-pro-v1:0"
    temperature: 0.1
    max-output-tokens: 1000
  retriever:
    max-results: 100
    min-score: 0.65
    max-context-length: 40000