apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.product }}-solace-certificates
data:
  SOLACE_CLIENT_CERT: |-
    -----BEGIN CERTIFICATE-----
    MIIFnzCCA4egAwIBAgIGAZTz1c7+MA0GCSqGSIb3DQEBCwUAMGQxCzAJBgNVBAYT
    AkNIMQ0wCwYDVQQIDARCZXJuMQ0wCwYDVQQHDARCZXJuMRQwEgYDVQQKDAtTQkIv
    RkZTL0NGRjEPMA0GA1UECwwGRGV2UmVsMRAwDgYDVQQDDAd0bXMtcGtpMB4XDTE1
    MDIxNDA3MDc0M1oXDTI3MDEyNDA3MDc0M1owfDELMAkGA1UEBhMCQ0gxDTALBgNV
    BAgMBEJlcm4xDTALBgNVBAcMBEJlcm4xHzAdBgNVBAoMFlNCQi9DRkYvRkZTL09V
    PXRtcy1zc3AxLjAsBgNVBAMMJXRtcy9wbGF0Zm9ybS90bXNzc3AvcC90bXMtc3Nw
    LWJhY2tlbmQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDKauvNJL1f
    vAVthHwe3KWOTWuV6imCsEtgLKviNGpSG1aUa/lATwysgVpZ3v9Pk9d/JSrdaX1t
    hfTHM4Np4kLWEyXo3UCy3Cl+Gj/VJhu0IO0lUng9L1TrWUB/dXeoXz6uYYBgtCOD
    /HWNdYaHGs/NvmOYOdh0cxROVUCM9/NijlZK2xwo0KV870bRS033gEcprzS1zpIL
    bbS/IYUuMUVsA0hfDpr8DADeRyf7uTzYgOV9O+NFejvc3dQ+xm1tKT/vR6y6Ui/m
    bMkjiudk1b0m7DofO112XzZeLstl9fzT2JYtdI7XZX5VB4U+DuT8GK2c+ufzu+zJ
    LnlcKjBwTr6WNwoR1MkfH/CYPv+Ola6qLB/yaiF72+YaRUl2faSMeX8OiZ8CNoko
    d5V/BRbx2q9q+StxBpJR8cgmfZpMbb76Y5BQzCK8HdeUouIlP+7iTxpPyRihgkZw
    fdsiHTpEKJUiuTrDhmW3ardpTEmVk+VdZZGOQocO7fSKkppEAmvPGixtXH8jXZEj
    Bhnz2Ti22kN0V7QqNITr1wd9HuA0oELqEZ7MWonxjk3nUCd72WdUZDe4yAHfImws
    uVkTzchfalv+13XCcM37MzCgT9O7/em7gil1HanEgVPEEd9oStIoEQv1pubE4Ah+
    CgaotedKXXB/YOfT5DmcAFFM3GZRR+iBkQIDAQABoz8wPTAJBgNVHRMEAjAAMA4G
    A1UdDwEB/wQEAwIFoDAgBgNVHSUBAf8EFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEw
    DQYJKoZIhvcNAQELBQADggIBABXmCsIMbpHwDVq3okmz1qj3Omzvw43MZCg6Eset
    HNLHICOMmT/3V11RogCx3qC+14yahOI7O3tnd2XNowyRnoBv/UCEjyY9kfCXLejE
    djui94mYLazsFJAJsxbXbGJfzt2Fni23jaCcQQ84oUoYY0KLBA37pfdAZaxW8wgY
    b6rqTupcs21vSMyLranEBgQrDESdYo2oGKiaDc1ckr9owoldZj6H0yEBzrNrQR1/
    EkN+ImimL4bGmQQ2LYFehoCcXlCdXuIqIbSkMM6yIgAM2AuD7QTrR+SfAZuUJpOL
    IfE7EK2Kas1wUbw71qYPrAX67PFvZ5RmjMD6LmyHHp/mMalK9xJQuc+qBaAnX0mu
    iRODjDrKsHej8BmPkkJxjvdC42uvlmQ2yrzLDJR+6Me37dt6pnnyIa5eWPV/yFV8
    u5JZ727h1i2+Cptme4bwAFjIRNzRiSom3JZQCpBoEvn+bHXlrv3QnQJYqgoAvv+C
    K7VC/DkpQdRWVz8VT+ri+SxAHQDOF7iy5EpXB42PwEK7AQGS7XCyK7NiaWu8CEdi
    E2rVS9uXIHl65p5vhdi4HaaQtYDTCLf6b1uqIWau9pwIqSx5Gw3WJujNTZZD7EKU
    xL2+Api4yRxefSEzrTk30UIS5uDkdED4q2RYfy9w0C3P1caXbajTD7FDt1FWoeUX
    zR5h
    -----END CERTIFICATE-----

