kind: Secret
apiVersion: v1
metadata:
  annotations:
    avp.kubernetes.io/path: kv/data/TRS-DSO-STTRS/TMS_SOLACE_SELFSERVICE_PORTAL/tms-ssp-chat-{{ $.Values.vaultStageSuffix }}
    avp.kubernetes.io/secret-version: "1"
  name: {{ $.Values.product }}
type: Opaque
stringData:
  CONFLUENCE_TOKEN: "<CONFLUENCE_TOKEN>"
  GITHUB_TOKEN: "<GITHUB_TOKEN>"
  BITBUCKET_TOKEN: "<BITBUCKET_TOKEN>"
  AWS_BEARER_TOKEN_BEDROCK: "<AWS_BEARER_TOKEN_BEDROCK>"
  SOLACE_PRIVATE_KEY: "<path:kv/data/TRS-DSO-STTRS/TMS_SOLACE_SELFSERVICE_PORTAL/broker-prod#SSL_PRIVATE_KEY#2>"

---

kind: Secret
apiVersion: v1
metadata:
  annotations:
    avp.kubernetes.io/path: kv/data/TRS-DSO-STTRS/TMS_SOLACE_SELFSERVICE_PORTAL/db-{{ $.Values.vaultStageSuffix }}
    avp.kubernetes.io/secret-version: "4"
  name: {{ $.Values.product }}-db
type: Opaque
stringData:
  DB_HOST: "<DB_HOST>"
  DB_NAME: "<DB_NAME>"
  DB_SCHEMA: "<DB_SCHEMA>"
  DB_USERNAME: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"

---

kind: Secret
apiVersion: v1
metadata:
  annotations:
    avp.kubernetes.io/path: kv/data/TRS-DSO-STTRS/TMS_SOLACE_SELFSERVICE_PORTAL/app-context-backend
    avp.kubernetes.io/secret-version: "3"
  name: {{ $.Values.product }}-app-context-backend
type: Opaque
stringData:
  OAUTH2_APP_CONTEXT_CLIENT_ID: "<OAUTH2_APP_CONTEXT_CLIENT_ID>"
  OAUTH2_APP_CONTEXT_CLIENT_SECRET: "<OAUTH2_APP_CONTEXT_CLIENT_SECRET>"
  OAUTH2_APP_CONTEXT_SCOPE: "<OAUTH2_APP_CONTEXT_SCOPE>"
